token: 'YOUR_BOT_TOKEN'
mode: 'dropdown'
mongodb_url: 'mongodb://localhost:27017'
guild_id: [123456789012345678]
extensions:
  - commands/deposit
  - commands/rate_dl
  - commands/set
  - commands/player